language: python
python:
  - "2.7"
before_install:
  - pip install pytest
  - export PYTHONPATH='.'
  - pip install biopython
# command to run tests
script:
  - py.test tests/test_ecvalidatingfiles.py
  - py.test tests/test_ecprediction.py