language: python
python:
  - "3.6"
before_install:
  - sudo apt-get update
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - echo ". $HOME/miniconda/etc/profile.d/conda.sh" >> ~/.bashrc
  - source ~/.bashrc
  - conda config --set always_yes yes --set changeps1 no
  - conda update -y conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda config --add channels conda-forge
  - conda config --add channels bioconda
  - conda create -q -n test-environment python=3.6 samtools=1.8 pandas=0.23.1 bowtie2=2.3.4.1 mash=2.0 bcftools=1.8 biopython=1.70 blast=2.7.1 seqtk=1.2 pytest=3.5 requests=2.22.0 portalocker=1.5.1
  - conda activate test-environment
  - python setup.py install

script:
  - pytest