about:
    license: MIT
    summary: Ectyper is a python script for serotyping e.coli genome
    author: Camille La Rose, Chad Laing, Sam Sung
    home: https://github.com/phac-nml/ecoli_serotyping/tree/moreserotype

package:
    name: ectyper
    version: 0.0.1

source:
    fn: moreserotype.zip
    url: https://github.com/phac-nml/ecoli_serotyping/archive/moreserotype.zip
    # md5: fb7b95f5c02e62e1fa3046f0c8e4b3a7

requirements:
    build:
        - python
    run:
        - bowtie2
        - python
        - samtools
        - bcftools

test:
    requires:
        - nose
    commands:
        - nosetests