about:
    license: MIT
    summary: Ectyper is a python script for serotyping e.coli genome
    author: Camille La Rose, Chad Laing, Sam Sung

package:
    name: ectyper
    version: 0.0.1

source:
    fn: moreserotype.zip
    url: https://github.com/phac-nml/ecoli_serotyping/archive/moreserotype.zip

requirements:
    run:
        - bowtie2 2.2.6*
        - python 3.5*
        - samtools 1.5*
        - bcftools 1.2*
