about:
    license: MIT
    summary: Ectyper is a python script for serotyping e.coli genomes
    author: Camille La Rose, Chad Laing, Sam Sung
    home: https://github.com/phac-nml/ecoli_serotyping

package:
    name: ectyper
    version: 0.0.9

source:
    git_url: https://github.com/phac-nml/ecoli_serotyping.git
    git_rev: 1.1.4

requirements:
    build:
        - python {{PY_VER}}*,>=2.7,<3.3|>=3.4
    run:
        - python
        - pandas
        - samtools
        - bowtie2
        - mash
        - bcftools
        - biopython
        - blast
        - seqtk
test:
    commands:
        - ectyper -h
