about:
    license: MIT
    summary: ECtyper is a python script for serotyping E. coli genomes
    author: Chad Laing, Camille La Rose, Sam Sung
    home: https://github.com/phac-nml/ecoli_serotyping

package:
    name: ectyper
    version: 0.1.0

source:
    url: https://github.com/phac-nml/ecoli_serotyping/archive/239795e27446c467c8100aeaa73a741efdbb026f.zip
    md5: d2cfb90afe8290b60c9c491aaee8db70

requirements:
    build:
        - python 3.6.3.*
        - pytest 3.*
    run:
        - python 3.6.3.*
        - pandas 0.21.0.*
        - samtools 1.5.*
        - bowtie2 2.3.0.*
        - mash 2.*
        - bcftools 1.8.*
        - biopython 1.69.*
        - blast 2.2.31 .*
        - seqtk 1.2.*
        - setuptools_scm 2.1.*
test:
    commands:
        - ectyper -h
