about:
    license: MIT
    summary: Ectyper is a python script for serotyping e.coli genomes
    author: Camille La Rose, Chad Laing, Sam Sung
    home: https://github.com/phac-nml/ecoli_serotyping

package:
    name: ectyper
    version: 0.9

source:
    path: ../../

requirements:
    build:
        - python {{PY_VER}}*,>=2.7,<3.3|>=3.4
        - future
        script: python setup.py install
    run:
        - python {{PY_VER}}*,>=2.7,<3.3|>=3.4
        - future
        - pandas
        - samtools
        - bowtie2
        - mash
        - bcftools
        - biopython
        - blast
        - seqtk
test:
    requires:
        - future
    commands:
        - ectyper -h
