about:
    license: MIT
    summary: Ectyper is a python script for serotyping e.coli genomes
    author: Camille La Rose, Chad Laing, Sam Sung
    home: https://github.com/phac-nml/ecoli_serotyping

package:
    name: ectyper
    version: 0.0.9

source:
    git_url: https://github.com/phac-nml/ecoli_serotyping.git
    git_rev: 1.1.4

requirements:
    build:
      noarch: python
    run:
        - python
        - pandas 0.21.0.*
        - samtools 1.5.*
        - bowtie2 2.3.0.*
        - mash 1.1.*
        - bcftools 1.6.*
        - biopython 1.69.*
        - blast 2.2.31 .*
        - seqtk 1.2.*
test:
    commands:
        - ectyper -h
